# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: '3.8'
services:

# Feedback prof
# Ports in env variables
  # use .dockerignore and copy . . on all dockerfile
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
      # add other environment variables here
    depends_on:
      db:
        condition: service_healthy
      # selon healthcheck (pg_isready)


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5


volumes:
  db_data:
    driver: local
