# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: '3.8'
services:

  app:
    build: .
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ROCKET_ADDRESS: ${ROCKET_ADDRESS}
    depends_on:
      blog-db:
        condition: service_healthy


  blog-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  db_data:
    driver: local
