# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: '3'
services:

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgres://thomas:admin@10.5.0.5:5432/blog
    depends_on:
      - blog-db
    networks:
      blog-network: 
        ipv4_address: 10.5.0.4

  blog-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      blog-network: 
        ipv4_address: 10.5.0.5


volumes:
  db_data:
    driver: local

networks:
  blog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
        - gateway: 10.5.0.1
