version: '3.8'

services:
  restaurant-php:
    container_name: restaurant-php
    build: .
    volumes:
      - web-vol:/var/www/html/public
    environment:
      - KERNEL_CLASS=${KERNEL_CLASS}
      - APP_SECRET=${APP_SECRET}
      - SYMFONY_DEPRECATIONS_HELPER=${SYMFONY_DEPRECATIONS_HELPER}
      - PANTHER_APP_ENV=${PANTHER_APP_ENV}
      - PANTHER_ERROR_SCREENSHOT_DIR=${PANTHER_ERROR_SCREENSHOT_DIR}
      - APP_ENV=${APP_ENV}
    env_file:
      - .env.prod

  nginx:
    container_name: restaurant-nginx
    image: nginx:stable
    restart: always
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - web-vol:/var/www/html/public
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - restaurant-php

volumes:
  web-vol:
