version: '3.8'

services:
  restaurant-php:
    container_name: restaurant-php
    build: .
    volumes:
      - web-vol:/var/www/html/public
    env_file:
      - .env.prod

  nginx:
    container_name: restaurant-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-vol:/var/www/html/public
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - restaurant-php

volumes:
  web-vol:
